# Generated by Django 5.2 on 2025-05-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_carouselitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
