# Generated by Django 5.2 on 2025-05-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_product_show_on_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
