# Generated by Django 5.2 on 2025-05-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_alter_carouselitem_caption_alter_carouselitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_carousel',
            field=models.BooleanField(default=False),
        ),
    ]
