# Generated by Django 5.2 on 2025-05-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
    ]
