# Generated by Django 5.2 on 2025-05-16 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_purchasehistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseHistory',
            new_name='PurchaseHistoryModel',
        ),
        migrations.AlterField(
            model_name='purchasehistorymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.userinfo'),
        ),
    ]
