# Generated by Django 5.2 on 2025-05-16 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_rename_purchasehistory_purchasehistorymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='product_name',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='details',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='PurchaseHistoryModel',
        ),
    ]
