# Generated by Django 5.2 on 2025-05-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_ordermaster_price_ordermaster_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='product_image_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
