# Generated by Django 5.2 on 2025-05-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_ordermaster_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='product_image_url',
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
