# Generated by Django 5.2 on 2025-05-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_razorpaypayment_delete_payment'),
        ('UserApp', '0008_remove_ordermaster_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminApp.product'),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
