# Generated by Django 5.2 on 2025-06-03 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_userinfo_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='balance',
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('placed', 'Order Placed'), ('dispatched', 'Dispatched'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='placed', max_length=20)),
                ('shipping_id', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserApp.ordermaster')),
            ],
            options={
                'db_table': 'OrderStatus',
            },
        ),
    ]
