# Generated by Django 5.2 on 2025-06-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_remove_userinfo_balance_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
