# Generated by Django 5.2 on 2025-06-03 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_orderstatus_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 3, 15, 40, 7, 963557, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
