# Generated by Django 5.2 on 2025-06-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_orderstatus_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='placed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
