# Generated by Django 5.2 on 2025-06-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_orderstatus_delivered_at_orderstatus_dispatched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
