# Generated by Django 5.2 on 2025-06-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_orderstatus_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='product_image',
        ),
    ]
