# Generated by Django 5.2 on 2025-06-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
